CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE crime_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (
  USER_ID NUMBER PRIMARY KEY,
  USERNAME VARCHAR2(100) UNIQUE,
  PASSWORD_HASH VARCHAR2(4000),
  ROLE VARCHAR2(50)
);

CREATE TABLE CRIME (
  CRIME_ID NUMBER PRIMARY KEY,
  CRIME_TYPE VARCHAR2(100),
  CRIME_DATE DATE,
  CRIME_LOCATION VARCHAR2(200),
  DESCRIPTION VARCHAR2(1000),
  VICTIM_NAME VARCHAR2(100)
);
-- OFFICERS TABLE
CREATE SEQUENCE officer_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE OFFICERS (
  OFFICER_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100),
  RANK VARCHAR2(100),
  CONTACT_NO VARCHAR2(20),
  STATION_ID VARCHAR2(20)
);

-- SUSPECTS TABLE
CREATE SEQUENCE suspect_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE SUSPECTS (
  SUSPECT_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100),
  AGE NUMBER,
  GENDER VARCHAR2(10),
  ADDRESS VARCHAR2(200),
  CRIME_RECORD_STATUS VARCHAR2(50)
);

-- CASES TABLE
CREATE SEQUENCE case_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE CASES (
  CASE_ID NUMBER PRIMARY KEY,
  CRIME_ID NUMBER,
  OFFICER_ID NUMBER,
  FIR_NO NUMBER,
  DATE_ASSIGNED DATE,
  STATUS VARCHAR2(50)
);

-- FIRS TABLE
CREATE SEQUENCE fir_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE FIRS (
  FIR_NO NUMBER PRIMARY KEY,
  COMPLAINT_ID NUMBER,
  FIR_DATE DATE,
  DETAILS VARCHAR2(1000)
);


